name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
  shell-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        run: |
          git diff ${{ github.event.pull_request.base.sha }}.. \
            --diff-filter=AM --name-only -- '*.sh' | while read script ; do \
              shellcheck $script || touch error ; \
          done
          test ! -e error
    
