name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release-paper: ${{ steps.release.outputs['paper--release_created'] }}
      release-velocity: ${{ steps.release.outputs['velocity--release_created'] }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release please
        uses: googleapis/release-please-action@v4
        id: release
  release-paper:
    needs: release-please
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.release-please.outputs.release-paper
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "tag=$(cat .release-please-manifest.json | jq -r .paper)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.tag }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: paper
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/paper:latest
            ghcr.io/${{ github.repository_owner }}/paper:${{ steps.vars.outputs.tag }}

  release-velocity:
    needs: release-please
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: needs.release-please.outputs.release-velocity
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "tag=$(cat .release-please-manifest.json | jq -r .velocity)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.tag }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: velocity
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/velocity:latest
            ghcr.io/${{ github.repository_owner }}/velocity:${{ steps.vars.outputs.tag }}
